name: Verify

on:
  push:
    branches-ignore: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Run check
      run: cargo check --all-targets
    - name: Build
      run: cargo build --all-targets --all-features
    - name: Run tests
      run: cargo test
    - name: Run Format
      run: cargo fmt --all --check
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Spell Check Repo
      uses: crate-ci/typos@v1.32.0
